results ={
    "studentName": "Venkatesh Manikandan Palani ",
    "seatNo": "22DBCAD073",
    "motherName": "Uma Maheshwari",
    "subjectCode": "8CSPL1141",
    "subjectName": "PROBLEM SOLVING TECHNIQUES USING C",
    "InternalMarks": "49.00",
    "ExternalMarks": "48.00",
    "internalExternalTotal": "97.00",
    "Grade": "0",
    "Pointer": "10.00",
    "creditPoint": "3.00",
    "earnedCredit": "3.00",
    "int": "50",
    "ext": "50",
    "sgpaCreditPointTotal": "19",
    "sgpaEarnedPointsTotal": "19",
    "sgpaObtainedMarks": "608.0",
    "cgTotal": "178.00",
    "sgpa": "9.37",
    "percentage": "93.54",
    "status": "Successful",
    "outOff": "650.0",
    "cgpaCGTotal": "178",
    "cgpaCreditPointTotal": "19.0",
    "cgpaEarnPointTotal": "19.0",
    "cgpa": "9.37",
    "cg": "30.00",
    "programName": "Bachelor of Computer Applications (Data Science)",
    "resultBlockStatus": "-",
    "resultBlockReason": "-",
    "ordinance": "-",
    "intPassing": "20.00",
    "extPassing": "20.00",
    "resultStatus": "Successful",
    "passingYear": "2022",
    "passingMonth": "December",
    "academicyear": "2022-2025",
    "instituteName": "School of Science Studies",
    "formPaymentStatus": "72722",
    "blockStatus": "false"
}

exam_schedule = {
    "examScheduleId": "5766",
    "ExamName": "153. REGULAR-2023,2022-III,V-SSCS-UG-SEE NOV 2024-2023,2022 BATCHES",
    "semesterId": "5",
    "semesterName": "V",
    "examScheduleTimetableId": "11854",
    "resultDeclarationDate": "2025-02-24",
    "universitySyllabusId": "182"
  }

print(results.keys())